### PR TITLE
Pending task type and security policy updated

### PR DESCRIPTION
**Pull request by storm20198**

### CODE REVIEW

**Review by ankitSharmaBeehyv — CHANGES_REQUESTED** [review]
@storm20198  I am seeing lots of mismatch between models. Decryption models have additional fields that are not there in encryption model. Please make sure CourtCase and CaseDecryptOther models are exactly same. CaseDecryptSelf should also be same except that it should have visibility PLAIN in all fields including accessCode field. 
Also make sure that we only use pattern id 003 in all places, that should simplify things as currently 002 is also used in some places and may contribute to mismatch

**Review by ankitSharmaBeehyv — CHANGES_REQUESTED** [review]
@storm20198 accessCode should not be masked in Self Decryption model otherwise join a case will fail.

**Review by ankitSharmaBeehyv — COMMENTED** [review]
witness first name last name  and middle name fields seem to be missing in other decrypt model, please check

**Review by manimaarans — APPROVED** [review]

**Comment by manimaarans** [comment]
Please address @ankitSharmaBeehyv comment later in a separate pr @storm20198

**Pull request merged**
